### PR TITLE
Submit VETravelDemandMM package for VE contribution review

### PR DESCRIPTION
**Pull request by lmwang9527**
By this pull request, the VETravelDemandMM package is submitted for the VE contribution review. 

Links to relevant documents:
- [Overview document of the package](https://cities-lab.github.io/VETravelDemandMM/Intro.html)
- [Slides for the package overview presentation](https://cities-lab.github.io/VETravelDemandMM/Overview_slides.html#1)
- [Responses to Contribution Review Criteria questions](https://cities-lab.github.io/VETravelDemandMM/Review.html)

Status of automated tests:
- [VETravelDemandMM package by itself](https://travis-ci.org/cities-lab/VETravelDemandMM): Travis-CI Build Status
- [With the whole VisionEval repo](https://travis-ci.org/cities-lab/VisionEval):  Travis-CI Build Status

### CODE REVIEW

**Comment by bstabler** [comment]
Thank you @lmwang9527 for the contribution.  The [Review Team](https://github.com/gregorbj/VisionEval/wiki/Review-Team-Charter) reviewed your contribution and voted as follows: 

  | Software | Documentation | Methods | notes
-- | -- | -- | -- | --
Accept | 1 | 6 | 6 | Counted @jrawbits as accept in all categories
Accept with revisions | 3 |   |   |  
Reject |   |   |   |  
Abstain | 3 | 1 | 1 | Counted Tufte as abstain
comments | For the software revisions, I   recommend splitting any functions which alter the VE framework (the   ‘helper     functions’) as a separate pull request, as Brian Gregor mentioned | I do have one minor comment   about the documentation that I noticed in the     Overview document of the package: The transit and walk TRFL models are   called with the function     R/PredictTransitTFL.R, not R/PredictTransitPMT.R (similar for the walk   models). |   |  
  |   | For the software revisions, I   recommend splitting any functions which alter the VE framework (the   ‘helper     functions’) as a separate pull request, as Brian Gregor mentioned. The   documentation is really quite     thorough, and the inclusion of the submitted manuscript (while I haven’t   read it) seems like an excellent     addition. |   |  

In addition, @mrspeel and I reviewed the contribution and had some [revisions](https://github.com/gregorbj/VisionEval/wiki/Example-Review#feedback) as well.  

Please address both the review team revisions and our revisions and then re-issue the pull request.  Assuming the revisions are completed, then we will accept the pull request.

**Comment by lmwang9527** [comment]
1. Travis returns a bunch of R package warnings that should be addressed,  such as ‘DoPredictions: no visible binding for global variable ‘model’.

    **Fixed with commit 24502591e49646a936e0accdd6132c5698060a1e**.
    
1. The dependent data packages (NHTS2009 and SLD) should be submitted.

    **They will be included in a new/separate pull request after this PR is merged.**
    
1. The overall VE project travis.yaml script should be updated to include the new module and dependent packages in the automatic testing. 

    **Done with commit e643502731e0d26f4fe3ddeefbfd97005c3c8c33**
    
1. The estimation methods should be revised to follow VE conventions. Some of these suggested revisions need to be discussed with the project team since we’re still figuring out how we all work together and incorporate additions.

    **I revised the variable names in estimation code in `data-raw`/ to follow VE conventions (commit 1b498d5760fac88c383705fd1c7c4bbf04a58080). There may be other places that I am happy to work with the review team and incorporate any apporpriate changes.**
    
1. update travis automated testing script to test new package

    **Done with commit e643502731e0d26f4fe3ddeefbfd97005c3c8c33**

2. revise the documentation/software to let the user know that the NHTS2009, SLD, confidential data for estimation, and estimation script are exceptions to the guidelines for various reasons.

    **A Data section is added to the Introduction vignette describing the data sources and the fact that confidential NTHS information is not included in the package (commit 6da6125cd696b17cc43302ee2a7df2899f0af871).**

3. add proof of ODOT release of ownership

    **Need Tara and Tony's help here.**

4. vignette and/or cheat sheet summarizing estimated functions and dependent variables

    **A `Variables Used in Models` subsection is added to the "Introduction to VETravelDemandMM" linking to Tara's cheat sheet (commit 6da6125cd696b17cc43302ee2a7df2899f0af871).**

1. For the software revisions, I recommend splitting any functions which alter the VE framework (the ‘helper functions’) as a separate pull request, as Brian Gregor mentioned.

    **I believe there is some confusion here - there is no function in the package that alters the VE framework. We did talk about some functions that are potentially helpful/useful to other packages, which may be better living upstream in the VE framework code. However, we didn't decide where it should be. These functions are all in R/DoPredictions.R (and, potentially, data-raw/EstModels.R), which could be easily moved to another place once we decide it. I am not sure it needs to be a separate pull request. Again I am happy to work with the review team and incorporate any apporpriate changes.**

1. The documentation is really quite thorough, and the inclusion of the submitted manuscript (while I haven’t read it) seems like an excellent addition.

1. I do have one minor comment about the documentation that I noticed in the Overview document of the package: The transit and walk TRFL models are called with the function R/PredictTransitTFL.R, not R/PredictTransitPMT.R (similar for the walk models).

    **Fixed with commit 9232f91bbb47dfa10b2569623c997fd79bb5562f**

**Comment by lmwang9527** [comment]
Oops, I think I made a mistake when rebasing this pull request and now it includes all the history since the pull request is created. It may be easier to close this pull request and for me  to create another pull request instead.

**Comment by bstabler** [comment]
@lmwang9527 please coordinate with VisionEval.org moving forward.  Thank you!

**Comment by DavidOry** [comment]
@lmwang9527: please submit the pull request to the `development` branch in this [repo](https://github.com/VisionEval/VisionEval-Dev/) and we'll have a look. Thank you!

**Comment by lmwang9527** [comment]
@DavidOry Will do. Could you fix the failed travis-ci buid for the `development` branch?

**Comment by DavidOry** [comment]
@lmwang9527: Yes. Go ahead and submit the PR for what you have and we'll do our best to do what's needed, including looking at the travis-ci bug/issue. We'll reach back out to you as needed.

**Comment by cities** [comment]
@DavidOry @bstabler can either of you confirm which repo I should use for my pull request to merge the VETravelDemandMM package? It seems that the [VisionEval/VisionEval-Dev](https://github.com/VisionEval/VisionEval-Dev) repo has been dormant for a few months (and without live integration tests in place) while the [gregorbj/VisionEval](https://github.com/gregorbj/VisionEval) repo is more active. Sorry it takes a while for me to get back to this.

**Comment by dflynn-volpe** [comment]
Hi Liming -- I'm going to update VisionEval/VisionEval-Dev to bring it up to speed with the recent significant updates, and will hook it up to Travis CI as well. You can make the pull request to that repository after I get it established. Thank you!

**Comment by dflynn-volpe** [comment]
@cities Please submit to [VisionEval/VisionEval-Dev](https://github.com/VisionEval/VisionEval-Dev/tree/development), `development` branch; Travis-CI is set up and passing on master, although some tests are timing out on development. We'll work on this.

**Pull request closed without merging**
